name: Build and Push to Dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bioregistry/bioregistry:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
